pipeline {
    agent any
    
    environment {
        RELEASE = '0.0.1'
    }
    
    stages {
        stage('Build') {
            agent any
            
            environment {
                LOG_LEVEL='INFO'
            }
            
            steps {
                echo "Building relese ${RELEASE} with log level ${LOG_LEVEL}"
                
            }
        }

        stage('Test') {
            steps {
                echo "Testing relese ${RELEASE}"
            }
        }

        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }
    }
    post {
        always {
            echo 'Prints success or failure'
        }
    }
}