pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'       
        }
    }
    
    // environment {
    //     VERSION = '0.0.1'
    //     VERSION_RC = "rc.2"
    // }
    
    stages {
        stage('Verify') {
            steps {
                sh '''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build  "$WORKSPACE/02/src/Pi.Web/Pi.Web.csproj'
            }
        }

        stage('Test') {
            steps {
                dir("$WORKSPACE/02/src") {
                    sh '''
                        dotnet test Pi.Math.Tests/Pi.Math.Tests.csproj
                        dotnet test Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                    '''      
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'dotnet $WORKSPACE/02/srcPi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll'
            }
        }
    }
}