def image

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    image = docker.build("jaimesalas/jenkins-pipeline-demos:0.0.2", "--pull -f 02/Dockerfile 02")
                    echo "${image}"
                }
            }
        }
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    withDockerRegistry([credentialsId: "docker-hub", url: ""]) {
                        image.push()
                    }
                }
            }
        }
    }
}