pipeline {
    agent any
    
    environment {
        RELEASE = '0.0.1'
    }
    
    stages {
        stage('Build') {
            agent any
            
            environment {
                LOG_LEVEL='INFO'
            }
            
            steps {
                echo "Building relese ${RELEASE} with log level ${LOG_LEVEL}"
                
            }
        }

        stage('Test') {
            steps {
                echo "Testing. Building relese ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
    }
}